### ISSUE TITLE
No instructions on setting up your database

### ISSUE THREAD

**Issue by erikdonohoo** [helyeahhh/Codev#2]
I understand you are using Xampp and probably have some MYSQL server setup and running, but your instructions do not explain how I should setup the DB. Its preferrable to use tools like Vagrant or Docker to abstract away all the setup so its really easy for others to get new projects up and running.

I would love if you could at the very least make updates to your README with instructions to get a DB setup, and you can't assume I have a Xampp folder to drag something into. You need the instructions to work for someone who has no other tools on their computer besides git, to be able to install and setup your code.

**Comment by helyeahhh** [comment]
Good day! Apologies on missing that part I've already updated my README and included the Database setup. On using Vagrant or Docker I'll definitely try to implement that next time and will add it to my list of expertise. 

Thanks!

**Comment by helyeahhh** [comment]
> I understand you are using Xampp and probably have some MYSQL server setup and running, but your instructions do not explain how I should setup the DB. Its preferrable to use tools like Vagrant or Docker to abstract away all the setup so its really easy for others to get new projects up and running.
> 
> I would love if you could at the very least make updates to your README with instructions to get a DB setup, and you can't assume I have a Xampp folder to drag something into. You need the instructions to work for someone who has no other tools on their computer besides git, to be able to install and setup your code.

**Comment by helyeahhh** [comment]
Hello Erik,

Apologies on reaching you out here but I updated my README instructions
again and the last commands will make my project work.

Thanks!
Vin
